import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./global.css";
import { getKindeServerSession } from "@kinde-oss/kinde-auth-nextjs/server";
import Navbar from "./components/navbar";
import Sidebar from "./components/sidebar";

import App from "./page";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "FDM Expenses",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { isAuthenticated } = getKindeServerSession();
  await isAuthenticated();
  return (
    <html lang="en">
      <body className={inter.className}>
        {(await isAuthenticated()) && (
          <>
            <Navbar />
            <Sidebar />
          </>
        )}
        {children}
      </body>
    </html>
  );
}
