import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./global.css";
import { getKindeServerSession } from "@kinde-oss/kinde-auth-nextjs/server";
import Navbar from "./components/navbar";
import Sidebar from "./components/sidebar";
import { findUser } from "./DB/find";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "FDM Expenses",
  description: "Generated by create next app",
  icons: { icon: "/favicon.ico"}
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { getUser } = getKindeServerSession();
  const user = await getUser();
  const currentUser = user ? await findUser(user.email) : null;

  return (
    <html lang="en">
      <body className={inter.className}>
        {currentUser && (
          <>
            <Navbar />
            <Sidebar
              status={currentUser.userDetails.userStatus}
              lineman={!!currentUser.employees}
            />
          </>
        )}
        {children}
      </body>
    </html>
  );
}
